### ISSUE TITLE
Saxon parser always expands entity references

### ISSUE THREAD

**Issue by yegor256** [yegor256/xembly#61]
```
javax.xml.parsers.ParserConfigurationException: Saxon parser always expands entity references
	at net.sf.saxon.dom.DocumentBuilderFactoryImpl.newDocumentBuilder(DocumentBuilderFactoryImpl.java:89)
	at org.xembly.Xembler.dom_aroundBody8(Xembler.java:216)
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.1`
