### ISSUE TITLE
NPE in RemoveDirective.exec() 

### ISSUE THREAD

**Issue by yegor256** [yegor256/xembly#63]
```
java.lang.NullPointerException
	at org.xembly.RemoveDirective.exec(RemoveDirective.java:61)
	at org.xembly.Xembler.apply_aroundBody2(Xembler.java:173)
	at org.xembly.Xembler$AjcClosure3.run(Xembler.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
	at org.xembly.Xembler.apply_aroundBody4(Xembler.java:166)
	at org.xembly.Xembler$AjcClosure5.run(Xembler.java:1)
```

**Comment by davvd** [comment]
@yegor256 tagged this issue with "bug"

**Comment by davvd** [comment]
@yegor256 thanks for the report, I topped your acc for 15 mins, payment ID `000-df463a6f`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.1`
