### ISSUE TITLE
non-thread-safe XPathFactory reused in XpathDirective.FACTORY

### ISSUE THREAD

**Issue by rgevaerd** [yegor256/xembly#82]
I believe this reuse of non-thread-safe object by xembly is causing https://github.com/zerocracy/farm/issues/1167#issuecomment-410485364:

```
java.lang.ArrayIndexOutOfBoundsException: 8
	at java.util.ArrayList.add(ArrayList.java:459)
	at net.sf.saxon.functions.FunctionLibraryList.addFunctionLibrary(FunctionLibraryList.java:44)
	at net.sf.saxon.Configuration.getBuiltInExtensionLibraryList(Configuration.java:1388)
	at net.sf.saxon.sxpath.AbstractStaticContext.setDefaultFunctionLibrary(AbstractStaticContext.java:127)
	at net.sf.saxon.xpath.JAXPXPathStaticContext.<init>(JAXPXPathStaticContext.java:56)
	at net.sf.saxon.xpath.XPathEvaluator.<init>(XPathEvaluator.java:71)
	at net.sf.saxon.xpath.XPathFactoryImpl.newXPath(XPathFactoryImpl.java:203)
	at org.xembly.XpathDirective.traditional(XpathDirective.java:138)
	at org.xembly.XpathDirective.exec(XpathDirective.java:98)
	at org.xembly.Xembler.apply(Xembler.java:155)
	at org.xembly.Xembler.dom(Xembler.java:210)
	at org.xembly.Xembler.xml(Xembler.java:256)
	at org.xembly.Xembler.xmlQuietly(Xembler.java:221)
	at com.zerocracy.claims.ClaimOut.postTo(ClaimOut.java:127)
	at com.zerocracy.pm.FootprintTest.lambda$addsInThreads$0(FootprintTest.java:88)
	at com.zerocracy.RunsInThreads.lambda$matchesSafely$0(RunsInThreads.java:90)
	at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
	at java.lang.Thread.run(Thread.java:745)
```
As you can see in XPathFactory documentation (https://docs.oracle.com/javase/8/docs/api/javax/xml/xpath/XPathFactory.html), it is not thread-safe and must never be used by more than one thread concurrently.
Xembly stores in the static final attribute `XpathDirective.FACTORY` an instance of such object and reuses it in many operations. Because of this, any multi-threaded application are subject to suffer misbehavior when using Xembly.
The error above is one example of such misbehavior that may happen when using Xembly in more than one thread. In this case this exception occurs on a race condition when calling Xembler.xmlQuietly on different threads, even with the threads using their own Xembler instance (because xembly internally will reuse the same XPathFactory causing the error).

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) please, pay attention to this issue

**Comment by 0crat** [comment]
@rgevaerd[/z](https://www.0crat.com/u/rgevaerd) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CBD1V4118) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by rgevaerd** [comment]
@carlosmiranda added more details to the description.

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#82](https://github.com/yegor256/xembly/issues/82); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
The job [#82](https://github.com/yegor256/xembly/issues/82) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CBD1V4118/2220173431); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@rgevaerd should be fixed in #85, I am working on releasing a patch.

**Comment by carlosmiranda** [comment]
@rgevaerd Released as `0.22.1`, see https://github.com/yegor256/xembly/releases. Please check and close if all is in order.

**Comment by rgevaerd** [comment]
@carlosmiranda Thanks

**Comment by 0crat** [comment]
Job was finished in 21 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
The job [#82](https://github.com/yegor256/xembly/issues/82) is now out of scope
